changelog:
  categories:
    - title: Enhancements 🎉
      labels:
        - enhancement
    - title: Bugfixes 🪲
      labels:
        - bug
    - title: Dependencies 👒
      labels:
        - dependency
    - title: Other Changes
      labels:
        - "*"
