import type { CodegenConfig } from '@graphql-codegen/cli'

const config: CodegenConfig = {
    schema: 'http://localhost:8080/graphql',
    documents: ['src/**/*.tsx', 'src/**/*.graphql'],
    ignoreNoDocuments: true, // for better experience with the watcher
    generates: {
        './src/gql/__autogenerated/': {
            preset: 'client'
        },
        './schema.graphql': {
            plugins: ['schema-ast'],
            config: {
                includeDirectives: true
            }
        }
    }
}

export default config
